### ISSUE TITLE
Error with jira access required bearer token inside header in the redirect SAML

### ISSUE THREAD

**Issue by gtjadsonsantos** [casbin/casdoor#2384]
https://github.com/casdoor/casdoor/assets/42282908/fd629656-cf39-436d-ab62-4d8aebae493a

**Comment by hsluoyz** [comment]
@gtjadsonsantos why close: https://github.com/casdoor/casdoor/issues/2381 and create new issue with broken video?

![image](https://github.com/casdoor/casdoor/assets/3787410/b3ee660f-eae2-442d-8dbd-cd8d72eb505a)

**Comment by gtjadsonsantos** [comment]
Yes, create one new to get tag `bug`, inside issue.

**Comment by gtjadsonsantos** [comment]
Added video

**Comment by hsluoyz** [comment]
@gtjadsonsantos what Jira version do you use? Is it local installation or Cloud? Please provide the link of the product

**Comment by gtjadsonsantos** [comment]
I use Jira Cloud, and this link to product https://www.atlassian.com/br/software/access

**Comment by Chinoholo0807** [comment]
@gtjadsonsantos  Currently, Jira Cloud do not support Casdoor directly. You can use miniOrange to integrate Casdoor and Jira Cloud. You can refer to the following docs:
- https://www.miniorange.com/atlassian-jira-cloud-single-sign-on-sso integrate Jira Cloud and miniOrange
- https://casdoor.org/docs/integration/java/jira/ integratge the Casdoor and miniOrange

**Comment by hsluoyz** [comment]
@gtjadsonsantos it's notable that:

1. This is Atlassian's limitation instead of Casdoor's limitation. Atlassian docs said it only supports a small selected set of identity providers: https://support.atlassian.com/provisioning-users/docs/supported-identity-providers/
2. Atlassian even doesn't support KeyCloak, another popular open-source SSO: https://community.atlassian.com/t5/Atlassian-Access-questions/How-can-I-configuration-SAML-in-Keyclock-to-use-atlassian-cloud/qaq-p/880278 and https://community.atlassian.com/t5/Atlassian-Access-questions/Jira-cloud-and-native-way-to-use-Keycloak/qaq-p/2090813 , Google search results shows that it seems have no direct way to connect Atlassian products with KeyCloak, except using a 3rd-party plugin like miniOrange.

So I'm afraid that based on the current situation, Casdoor can do nothing else to help your case.
