### ISSUE TITLE
cas client raise "not well-formed (invalid token)" when connect casdoor cas service

### ISSUE THREAD

**Issue by goodosoft** [casbin/casdoor#2400]
cas client: django-cas-ng: https://github.com/django-cas-ng/django-cas-ng
url: /accounts/login?next=%2F&ticket=ST-2301137533117928606
ParseError at /accounts/login
not well-formed (invalid token): line 1, column 1825
Django Version: | 4.2.6
-- | --
ParseError
not well-formed (invalid token): line 1, column 1825
/usr/local/lib/python3.12/xml/etree/ElementTree.py, line 1323, in XML
django_cas_ng.views.LoginView
/usr/local/bin/python
3.12.0

and this cas client works well when connect to my another cas service write by django-mama-cas.

**Comment by hsluoyz** [comment]
@goodosoft can you share a full example code in the github repo format? Remove your crendential code in the repo, only keep the CAS code

**Comment by Songjf-ttk** [comment]
@goodosoft Hello, the reason is that Casdoor's frontend and backend are listening on different ports. Based on my attempts, perhaps you set the **CAS_SERVER_URL** variable in settings.py to the frontend's URL. This way, it can redirect to the login page, and after logging in,  **django-cas-ng** will go to verify the ticket, but this request will also be sent to the frontend, so the backend will miss this request, and then the above error will occur.

**Comment by hsluoyz** [comment]
@goodosoft it runs well on my side:

![image](https://github.com/casbin/casdoor/assets/3787410/655a833c-28b0-4eac-9f7d-d5c3ff14a6df)

Try this example: https://github.com/django-cas-ng/example , change the CAS server to Casdoor demo site:

```py
# CAS_SERVER_URL = 'https://django-cas-ng-demo-server.herokuapp.com/cas/'
CAS_SERVER_URL = 'https://door.casdoor.com/cas/casbin/cas-java-app/'
```

You need to deploy Casdoor in prod mode: https://casdoor.org/docs/basic/server-installation#production-mode

And create the application for CAS: https://casdoor.org/docs/how-to-connect/cas
