### ISSUE TITLE
bug: openapi-generator-cli error for typescript-axios

### ISSUE THREAD

**Issue by 0xyjk** [casbin/casdoor#2412]
i'm trying to use [OpenAPI Generator](https://openapi-generator.tech/) to generate client side code for casdoor, but got this error
<img width="1466" alt="image" src="https://github.com/casdoor/casdoor/assets/110372666/b7d25f09-1c1d-4611-8d99-37d0699244f1">

please fix the swagger issue

**Comment by hsluoyz** [comment]
@0xyjk can you make a PR?

**Comment by hsluoyz** [comment]
@0xyjk what language of client side code do you want to generate?

**Comment by waynr** [comment]
I've run into this issue as well when attempting to use a different client generator (https://crates.io/crates/paperclip). I don't necessarily think the problem is in the target language but in whether or not the client generator tool requires strict adherence to the OpenAPI spec -- I was able to generate a client using a different generator with seemingly more lax interpretation of the spec (https://github.com/swagger-api/swagger-codegen).

The casdoor swagger json that I downloaded from a locally dev instance of casdoor definitely does not follow the spec. For example, consider the `/api/add-user-keys` endpoint definition:

```
        "/api/add-user-keys": {
            "post": {
                "tags": [
                    "User API"
                ],
                "operationId": "ApiController.AddUserkeys"
            }
        },
```

This contains one [pathItem](https://github.com/OAI/OpenAPI-Specification/blob/78170608af208da8165ab095715e5cb9ff715f47/schemas/v2.0/schema.json#L306) with an [operation](https://github.com/OAI/OpenAPI-Specification/blob/78170608af208da8165ab095715e5cb9ff715f47/schemas/v2.0/schema.json#L238) called ["post"](https://github.com/OAI/OpenAPI-Specification/blob/78170608af208da8165ab095715e5cb9ff715f47/schemas/v2.0/schema.json#L324-L326). The `operation` type in this spec [requires a `responses`](https://github.com/OAI/OpenAPI-Specification/blob/78170608af208da8165ab095715e5cb9ff715f47/schemas/v2.0/schema.json#L240-L242) field.

My interpretation/understanding of the way the spec is defined gets a little fuzzy at this point (this is my first time reading an openapi spec) but it [looks to me like the responses field requires a minimum of one element](https://github.com/OAI/OpenAPI-Specification/blob/78170608af208da8165ab095715e5cb9ff715f47/schemas/v2.0/schema.json#L347); this interpretation makes sense to me since I don't see why an HTTP API endpoint+operation would not be expected to return any response at all. In fact, [IETF RFC 9110](https://www.rfc-editor.org/rfc/rfc9110.html#name-messages) agrees with this interpretation:

> A server responds to a client's request by sending one or more "response" messages, each including a status code (Section 15). 

(also, I've never encountered a situation where a HTTP request by a client not followed by a HTTP response from the server was anything other than an timeout error)

**Comment by waynr** [comment]
So to expand on why I think that it's most likely a casdoor spec issue (rather than a generator or target language issue), here is the struct field definition in `paperclip` that makes the `responses` field for operations required:

* https://github.com/paperclip-rs/paperclip/blob/555a460cdfbc295edb504c3d7f441253a5c681ae/core/src/v2/models.rs#L715

If you're unfamiliar with rust and its widely used serialization framework, what makes this field required in this generator and what makes it fail to generate code for casdoor's swagger spec is  the fact that it's

```
pub responses: BTreeMap<String, Either<Reference, R>>,
```
rather than
```
pub responses: Option<BTreeMap<String, Either<Reference, R>>>,
```

Based on both the swagger/openapiv2 spec definition and the fact that HTTP requests always require at least once response according to IETF RFC 9110, I believe paperclip's behavior here is correct.

I suspect since casdoor is written in golang that somewhere there is a `json: omitempty` tag on the `responses` field in the operation struct and that whatever tooling is populating the data structure that defines casdoor's openapi spec is neglecting to include a valid response. Or maybe it's not generated at all? Is that file just manually maintained [here](https://github.com/casdoor/casdoor/blob/master/swagger/swagger.json)?

**Comment by waynr** [comment]
Aha, I found the source of the error I encountered. It looks like casdoor uses a framework called `beego` which generates swagger spec based on [comment annotations on api controller methods](https://github.com/beego/beedoc/blob/master/en-US/advantage/docs.md#application-comment). For example for the endpoint `paperclip` was complaining to me about there are no annotations indicating what responses to expect for success OR failure: https://github.com/casdoor/casdoor/blob/b985bab3f3cddb550c22baa8f313a621e2259fc9/controllers/user.go#L579-L599

```go
// AddUserKeys
// @Title AddUserKeys
// @router /add-user-keys [post]
// @Tag User API
```

To generate correct swagger docs this would have look more like
```go
// AddUserKeys
// @Title AddUserKeys
// @router /add-user-keys [post]
// @Tag User API
// @Success 200 {int} int The count of filtered users for an organization
```

**Comment by hsluoyz** [comment]
@0xyjk @waynr partially fixed for Java client: https://github.com/casbin/casdoor/commit/21f394847e5b384875f0f4eb9ea456e3f24ef80f
