### ISSUE TITLE
auto-generate/consume invitation code

### ISSUE THREAD

**Issue by jump2cn** [casbin/casdoor#2534]
Hi team,

In my test, I found the application invitation code can only be added manually by the admin, once someone knows the invitation code, he can register unlimited with the same code.

I think a better way is for the admin to have an API to send an invitation email, and once the mail receiver finished the register action, that invitation code will be disabled.

**Comment by hsluoyz** [comment]
@jump2cn hi, can you make a PR?

**Comment by link89** [comment]
Or more general, instead of just verify invitation code, casdoor should allow user to set a `registerVerifyUrl` and send a request with the form body to it, so that user can not only verify the inviation code, but also setup their rules against other information, for example, the domain name of email address, etc.

**Comment by sp71** [comment]
Forked repo created PR for invite feature that can be used as reference here
 https://github.com/casgate/casgate/pull/15

**Comment by hsluoyz** [comment]
Invitation admin pages added here: https://door.casdoor.com/invitations , needs to execute them
