### ISSUE TITLE
Support S3-compliant storage providers like DigitalOcean

### ISSUE THREAD

**Issue by iyobo** [casbin/casdoor#2541]
There are many Storage providers that are fully S3 compliant but require a different endpoint e.g DigitalOcean spaces.

Right now when defining a Storage provider, when I try to use a DigitalOcean spaces endpoint (As an AWS S3 provider type), it is converting the endpoint I put in before making the request i.e:

https://mycdn.nyc3.digitaloceanspaces.com -> https://mycdn.s3.nyc3.amazonaws.com .

The endpoint field should not be modified.

**Comment by hsluoyz** [comment]
@iyobo can you show the location of the code (whether inside Casdoor or not) that changes your endpoint? https://mycdn.nyc3.digitaloceanspaces.com/ -> https://mycdn.s3.nyc3.amazonaws.com/

**Comment by iyobo** [comment]
When creating a Storage provider, I put in this 
<img width="740" alt="image" src="https://github.com/casbin/casdoor/assets/5804246/5b557ddb-6eb8-4a3e-a851-95c411873c4d">

But then when I try to upload an avatar for a user, I get the error:
<img width="1399" alt="image" src="https://github.com/casbin/casdoor/assets/5804246/94c52a17-045e-4739-a305-1c7369ac1064">

Notice how it disregards the "Endpoint" field entered in the provider definition.

**Comment by hsluoyz** [comment]
@iyobo fixed by: https://github.com/casbin/casdoor/commit/f8905ae64c1967062c9b02a95f02fa5d9201c5f7

Configure example is: https://door.casdoor.com/providers/admin/provider_storage_digitalocean , the most important field is `Endpoint`. Remember:

- No “https” prefix
- No bucket name
- No "cdn" subpath

So it should be `nyc3.digitaloceanspaces.com` instead of something like `https://casdoor.nyc3.cdn.digitaloceanspaces.com`, which is shown directly in the Digital Ocean portal.

![image](https://github.com/casbin/casdoor/assets/3787410/0ed64def-9c22-407f-9979-d6646266e780)
