### ISSUE TITLE
Google and Github auth doesn't work

### ISSUE THREAD

**Issue by artem-avanesov** [casbin/casdoor#332]
https://door.casbin.com/login

**Comment by hsluoyz** [comment]
@artem-avanesov what does the error say? Is it just a configuration issue? Can you try it again to see if fixed?

**Comment by seriouszyx** [comment]
@hsluoyz I guess he wants to say our demo site for Casdoor doesn't work. 

![image](https://user-images.githubusercontent.com/33992371/142595827-d53ff2c0-b687-4cca-a6ac-7aedd79471a8.png)
![image](https://user-images.githubusercontent.com/33992371/142595883-ea3cb59b-4b59-4b2d-91b8-27ad50e51e26.png)

**Comment by hsluoyz** [comment]
@artem-avanesov I think this is intended instead of a bug, because we just disabled signing up via OAuth in built-in application previously: https://door.casbin.com/applications/app-built-in

Now it's all opened. You can try again.

![image](https://user-images.githubusercontent.com/3787410/142611284-f260aa97-57a3-4237-aeee-7c47e3d764dc.png)
