### ISSUE TITLE
Add captcha before sending Email and phone verification code

### ISSUE THREAD

**Issue by hsluoyz** [casbin/casdoor#58]
We will use: https://github.com/dchest/captcha like how we did in Casnode

![image](https://user-images.githubusercontent.com/3787410/118351295-bf558080-b58d-11eb-8301-e2034633f658.png)

**Comment by EmperorYP7** [comment]
I'd like to take this up.

**Comment by hsluoyz** [comment]
@EmperorYP7 sure. See how it works: https://github.com/casbin/casnode/search?q=captcha

**Comment by EmperorYP7** [comment]
I ran into a couple of issues while setting up the dev environment. While I work on it, I think it'd be great if we could Dockerize this project to be more developer-friendly. Setting up a docker-compose command should do the trick.

**Comment by hsluoyz** [comment]
@EmperorYP7 what issues do you encounter?

**Comment by EmperorYP7** [comment]
<img width="1256" alt="Screenshot 2021-05-17 at 10 36 24 PM" src="https://user-images.githubusercontent.com/62606998/118529039-b10b8e00-b760-11eb-92de-ed9809d8e725.png">

Something's wrong with MySQL user-config. 
P.S: Apologies for the dormancy, there are some connection issues due to cyclone Tauktae in Mumbai, India. I'll be fixing this ASAP.

**Comment by hsluoyz** [comment]
@EmperorYP7 you should setup your own DB's credential, see: https://github.com/casbin/casdoor#config

**Comment by hsluoyz** [comment]
Fixed by: https://github.com/casbin/casdoor/pull/70
